make optimized adj matrix from csv file
xthebat/iu4-2k21-mlni pull request #10
Opened 2021-03-14 21:02 UTC by andrey308

Add test csv files that contains mazes 3x3 and 6x5. Create a functional that provides creation an adjacency matrix from maze, and put it into csv file 'adj.csv'.

2021-03-17 07:16 UTC, xthebat requested changes
Нужны:
- unit-test
- поиск кратчайшего пути
- комментарии как жить с paths
- опционально удаление стенки

PS: когда тестил, path выглядит очень жестко, возможно если заменить хотя бы на namedtuple станет намного понятнее, но сейчас сложна

2021-03-17 07:16 UTC, xthebat commented on mironov_aa_iu4_83/task01/main.py
> +    for side in ['left', 'right', 'up', 'down']:
прикольно конечно :) Но я бы сделал проще, см. код с семинара 6-го

```python
def neighbours(image: Array, row: int, col: int):
    rows, cols, _ = image.shape
    for drow, dcol in ((-1, 0), (1, 0), (0, -1), (0, 1)):
        next_row = row + drow
        next_col = col + dcol
        if 0 <= next_row < rows and 0 <= next_col < cols:
            yield next_row, next_col
```

Работать по идее будет быстрее и в самих внутренностях в программе я не вижу особо смысла в строках left, right и т.п.

2021-03-17 07:16 UTC, xthebat commented on mironov_aa_iu4_83/task01/main.py
> +        if check_node(nodes, matrix[y][x + 1], x, y):                   # Right
AFAIK: исключения не очень быстрый механизм, да код веселенький :) Но я бы сделал через проверку индексов, что выходит или нет за границу массива.

2021-03-17 07:16 UTC, xthebat commented on mironov_aa_iu4_83/task01/main.py
> +        try:
не очень это хорошо большой кусок кода пихать в try-except и при этом дропать исключение. Это ведет к возможным большим проблемам при отладке. Так как можно пропустить где-то, что может не намеренно возникнуть ошибка выхода за границу и она будет съедена. После этого остается пожелать только happy-debugging

В целом строить логику на исключениях - это не самая лучшая идея

2021-03-17 07:16 UTC, xthebat commented on mironov_aa_iu4_83/task01/main.py
> +    for side in ['left', 'right', 'up', 'down']:
ну также можно использовать neighbours, кстати в них уже учтено, что за границы мы выйти не можем + фильтрануть сразу по тем ячейкам, которые являются путями см. https://github.com/xthebat/iu4-2k21-mlni/pull/12#pullrequestreview-613945389

2021-03-17 07:16 UTC, xthebat commented on mironov_aa_iu4_83/task01/main.py
> +                if (x + corr_x, y + corr_y) in paths.keys():
тут сложно и страшно, я бы разбил это на функции

2021-03-17 07:16 UTC, xthebat commented on mironov_aa_iu4_83/task01/main.py
> +def csv_adj_matrix(adj, nodes_num):
наверное можно разделить эту функцию - одна преобразование в матричный формат, а вторая уже запись

2021-03-17 07:16 UTC, xthebat commented on mironov_aa_iu4_83/task01/main.py
> +    adj_matrix = {}
код из main по обработке я бы вынес в отдельную функцию

2021-03-17 07:16 UTC, xthebat commented on mironov_aa_iu4_83/task01/main.py
> +    print(f'Nodes: {nodes}')
....оставил только вызов функций обработчиков и печать результатов

2021-03-17 07:16 UTC, xthebat commented on mironov_aa_iu4_83/task01/main.py
> +                    paths.update({(x, y): f'{nodes[(x + corr_x, y + corr_y)]}_{side}'})
Здесь тоже что-то страшное. Просто не очень понятно, что хранится в paths, где-то это hash, где-то это строка с указанием сайда, где-то другая ячейка из paths и еще оборачиваение try-except. Без комментариев точно не понятно, что происходит

2021-03-20 16:43 UTC, andrey308 commented on mironov_aa_iu4_83/task01/main.py
> +        if check_node(nodes, matrix[y][x + 1], x, y):                   # Right
Согласен, через if даже понятнее получается. Так и сделаю

2021-03-20 16:46 UTC, andrey308 commented on mironov_aa_iu4_83/task01/main.py
> +        try:
Вообще, насколько я знаю, исключения работают быстрее чем проверка через if в том случае, когда разработчик уверен, что подавляющее большинство проверок не закончатся перехватом исключений. Но с точки зрения читабельности наверное правильно сделать проверку через if.

2021-03-20 16:55 UTC, andrey308 commented on mironov_aa_iu4_83/task01/main.py
> +def csv_adj_matrix(adj, nodes_num):
Принято, так и сделаю

2021-03-20 17:15 UTC, andrey308 commented on mironov_aa_iu4_83/task01/main.py
> +                    paths.update({(x, y): f'{nodes[(x + corr_x, y + corr_y)]}_{side}'})
Строка формата f'{node}_{side}' нужна идентификации, с какой стороны мы считаем путь от узла. Это необходимо, так как мы можем из одного узла прийти в другой аж 4-мя разными путями. Чтобы не было таких неоднозначных событий я решил оптимизировать такие ситуации и если действительно существует несколько путей из одного узла в другой - выбирается наименьший. Это правда не дает решить допольнительную задачу с "сломанной стенкой", но я буду разбираться с этим позже.

Другая ячейка из path используется в дальнейшем для подсчета пути. Я таким образом помечаю, что конкретная ячейка принадлежит неразрывному пути с идентификатором f'{node}_{side}'. Таким образом, пока алгоритм не поймет, что путь окончен с двух сторон узлами - этот путь будет идентифицирован тем узлом, из которого он начался.

Хэш - это объективно костыль. Я нашел в своем алгоритме косяк - так как мы всегда движемся справа налево и снизу вверх, возможны ситуации, когда мы просто не можем идентифицировать путь никаким узлом, тк путь встретился впервые. Чтобы эту ситуацию обыграть - я беру хэш от координат. В дальнейшем, когда путь упрется в узел, я все ячейки данного пути буду идентифицировать данным узлом, а не хэшом.

2021-03-20 21:51 UTC, andrey308 commented on mironov_aa_iu4_83/task01/main.py
> +                if (x + corr_x, y + corr_y) in paths.keys():
Разбить на функции не получилось, добавил комментариев как это работает

2021-03-20 21:51 UTC, andrey308 commented on mironov_aa_iu4_83/task01/main.py
> +    adj_matrix = {}
Разбил функционал на разные файлы, надеюсь, будет понятнее

2021-03-20 21:57 UTC, andrey308 commented on mironov_aa_iu4_83/task01/main.py
> +    for side in ['left', 'right', 'up', 'down']:
Мой алгоритм строит сразу оптимизированную матрицу связанности, в которой нет лишних узлов. Также, если существует два пути из одного узла в другой - берется наименьший. Описал это все в комментариях. Возможно не оптимальный вариант, но все происходит за один проход лабиринта.

2021-03-20 21:57 UTC, andrey308 commented on mironov_aa_iu4_83/task01/main.py
> +    print(f'Nodes: {nodes}')
Так и сделал

2021-03-22 05:31 UTC, xthebat commented on mironov_aa_iu4_83/task01/main.py
> +                    paths.update({(x, y): f'{nodes[(x + corr_x, y + corr_y)]}_{side}'})
На мой взгляд здесь без использование класса будет сложно сделать без таких костылей. Пока новые коммиты не смотрел, но в целом лучше подумать, чтобы заменить на класс примерно такой:

```python
class Way(object):
    def __init__(self, node, direction, ....):
```

2021-03-26 09:06 UTC, xthebat approved these changes
Остальное ревью находится в: https://github.com/xthebat/iu4-2k21-mlni/tree/CR-A308-Task01

Переделал код более ООП-like, в основном все хорошо, что сильно не понравилось:
- Использование update когда добавляешь один ключ (зачем?)
- Объединить в одну сущность side и id и hash

- Не нашел, где Дийкстра на полученную из лабиринта матрицу накидывается
- Если не будешь ломать стены, то в остальном все зачтено.

Могу вмерджить после того, как заберешь мой CR и добавишь Дийкстру в код тестов совместно с генерацией adj

2021-03-26 09:06 UTC, xthebat commented on mironov_aa_iu4_83/task01/dkstr.py
> +def indices(m):
Я бы сделал это на product из itertools, пример кода писали rangend - более общий вариант. И ты этой функцией почему-то пользуешься не везде :)

2021-03-26 09:06 UTC, xthebat commented on mironov_aa_iu4_83/task01/main.py
> +        if pointer_in_maze_scope(x + corr_x, y + corr_y, matrix):
только это не pointer, а point_in_maze_scope

2021-03-26 09:06 UTC, xthebat commented on mironov_aa_iu4_83/task01/main.py
> +            if start_or_end_position(x, y, len(row), len(maze)):
Я бы разбил эту функцию на две `is_start(x, y, maze) or is_end(x, y, maze)`

2021-03-26 09:06 UTC, xthebat commented on mironov_aa_iu4_83/task01/main.py
> +                nodes.update({(x, y): next_node_id(nodes)})
В чем такая любовь к update? Может быть я что-то не понял? Разве так не будет проще 
и читабельней:

```python
nodes[(x, y)] = next_node_id(nodes)
```
ИМХО: Особенно в трехэтажных конструкция совсем страшно становится с update

2021-03-26 09:06 UTC, xthebat commented on mironov_aa_iu4_83/task01/main.py
> +    scan_maze(maze, adj_dict, paths, nodes)
Да, без классов грустновато :)

2021-03-26 09:06 UTC, xthebat commented on mironov_aa_iu4_83/task01/neighbours.py
> +        corr_x, corr_y = get_corrections(side, invert=True)
Кстати, correction прям просится заменит себя на словарик. И вопрос: зачем нужен invert?

2021-03-26 09:06 UTC, xthebat commented on mironov_aa_iu4_83/task01/neighbours.py
> +                adj_dict.update({
```python
frm = nodes[(x + corr_x, y + corr_y)]
to = ndoes[(x, y)]
adj_dict[(frm, to)] = 1
```
Или вынести в функцию ```adj_add_link```. То что мы "пока не проходили классы" - не запрещает использовать парадигму ООП

2021-03-26 10:50 UTC, andrey308 commented on mironov_aa_iu4_83/task01/neighbours.py
> +        corr_x, corr_y = get_corrections(side, invert=True)
По факту функция get_corrections используется для двух задач: получить позицию указателя на ячейку, когда мы проверяем соседей, чтобы определить их тип, а также, чтобы проверить соседей ячейки "путь" для получения информации о связи соседа с существующим узлом. Если таковая связь есть, то она будет выглядеть как, например, 0_right. Это значит что путь пришел из узла 0, с правой стороны.

2021-03-26 10:53 UTC, andrey308 commented on mironov_aa_iu4_83/task01/neighbours.py
> +                adj_dict.update({
Справедливости ради, по какой-то причине с особой осторожность отношусь к классам. Почему то всегда кажется, что без них можно вполне обойтись в данной ситуации. С точки зрения читабельности - наверное классы читаются лучше. Попробую на выходных что-нибудь придумать с классами

2021-03-26 15:44 UTC, xthebat commented on mironov_aa_iu4_83/task01/neighbours.py
> +                adj_dict.update({
Комменты немного не удел оказались :) см код, который я коммитнул в свой репозиторий в ветку CR-A308-Task01

2021-04-04 06:02 UTC, merged