Task01
xthebat/iu4-2k21-mlni pull request #11
Opened 2021-03-14 21:23 UTC by statizarm

2021-03-17 06:50 UTC, xthebat requested changes
Нужны:
- комментарии как работает логика с prev
- unit-test
- "оптимизация" графа

2021-03-17 06:50 UTC, xthebat commented on shushuev_ai/task01/main.py
> +    filename = args[1] if len(args) > 1 else input("Enter path to csv file: ")
Не используйте input - я говорил об этом на семинарах. Это неудобно для тестирования и бессмысленно (в таком варианте консольные программы практически никогда не используются)

2021-03-17 06:50 UTC, xthebat commented on shushuev_ai/task01/main.py
> +    row_gen = ([int(num) for num in line.split(' ')] for line in file)
Отдельно можно не создавать генератор, а сразу писать его в if

2021-03-17 06:50 UTC, xthebat commented on shushuev_ai/task01/main.py
> +    file = open(filepath, "rt")
Не оставляйте файлы открытыми - используйте with

2021-03-17 06:50 UTC, xthebat commented on shushuev_ai/task01/main.py
> +        for i in range(len(row)):
наверное i лучше назвать col :)

2021-03-17 06:50 UTC, xthebat commented on shushuev_ai/task01/main.py
> +                if prev == 1:
Логика работы с prev - непонятна :( Не говорю, что не правильно или это плохо, в комментариях хотел бы описание как это работает. На мой взгляд нужно тыкаться в каждого соседа на каждой ячейки, которая является "проходом". См. https://github.com/xthebat/iu4-2k21-mlni/pull/12#pullrequestreview-613945389

2021-03-21 08:28 UTC, statizarm commented on shushuev_ai/task01/main.py
> +                if prev == 1:
я изменил в новой версии алгоритм построения, теперь там нет prev. Но, в этой версии он нужен был как ограничитель и переменная которая хранит в себе значение предыдущей ячейки в строке (для 0й чейки значение предыдущей ячейке в этой же строке должно быть 0)

2021-03-21 08:31 UTC, statizarm commented on shushuev_ai/task01/main.py
> +                if prev == 1:
Если prev убрать, то для того чтобы посмотреть предыдущее значение нужно было бы проверять j на 0, чтобы не вылететь за границы массива

2021-04-04 06:16 UTC, merged