Task01
xthebat/iu4-2k21-mlni pull request #12
Opened 2021-03-15 06:03 UTC by Dsin72

Первое дз
- добавила функцию чтения лабиринта
- добавила функцию парсинга лабиринта
- добавила файл с лабиринтом
- добавила создание матрицы смежности из карты лабиринта

2021-03-17 06:44 UTC, xthebat requested changes
Не очень понятно решение с prev как это работает, но вроде потестил - похоже.

Мой вариант:
```python
def rangend(*args: int) -> Iterator:
    return itertools.product(*(range(it) for it in args))


def neighbours(maze: List[List[int]], row: int, col: int):
    rows = len(maze)
    cols = len(maze[0])
    for drow, dcol in ((-1, 0), (1, 0), (0, -1), (0, 1)):
        next_row = row + drow
        next_col = col + dcol
        if 0 <= next_row < rows and 0 <= next_col < cols:
            yield next_row, next_col


def get_or_create_node(nodes, row, col):
    if (row, col) not in nodes:
        nodes[(row, col)] = max(nodes.values()) + 1 if len(nodes) else 0
    return nodes[(row, col)]


def generate_graph(maze: List[List[int]]):
    rows = len(maze)
    cols = len(maze[0])

    nodes = dict()
    adj = dict()

    for row, col in filter(lambda it: maze[it[0]][it[1]], rangend(rows, cols)):
        node_id = get_or_create_node(nodes, row, col)
        links = dict()
        adj[node_id] = links
        for neighbour_row, neighbour_col in filter(lambda it: maze[it[0]][it[1]], neighbours(maze, row, col)):
            neighbour_id = get_or_create_node(nodes, neighbour_row, neighbour_col)
            links[neighbour_id] = 1

    return nodes, adj


def adjacency_matrix(adj):
    size = len(adj)
    matrix = [[0] * size for _ in range(size)]
    for node, links in adj.items():
        row = int(node)
        for other, length in links.items():
            col = int(other)
            matrix[row][col] = length
    return matrix
```

нужны:
- unit-test
- "оптимизация" графа

2021-03-17 06:44 UTC, xthebat commented on sinyutina_ds/task01/main.py
> +        path = input()
не нужно останавливать программу после выдачи ошибки. Вспомните любую линуксовую утилиту, если что-то задали неправильно. Ругается и выходит.
То есть я бы написал так:
```python
if len(args) != 2:
    print("Wrong number of args, just file name required")
    sys.exit(-1)
```

2021-03-17 06:44 UTC, xthebat commented on sinyutina_ds/task01/main.py
> +    vertex_map = [['' for i in range(len(row))] for row in maze_map]
Почему id вертексов сделаны строками? Где-то они используются как int, где-то как строка

2021-03-17 06:44 UTC, xthebat commented on sinyutina_ds/task01/main.py
> +    for i in range(len(maze_map[0])):
Если я правильно понял, то здесь выполняется построение матрицы смежности, но вопрос, почему проходится только первый столбец?

2021-03-17 06:44 UTC, xthebat commented on sinyutina_ds/task01/main.py
> +
Функция явно требует того, чтобы бы разделенной как минимум на две подфункции.

2021-03-17 06:44 UTC, xthebat commented on sinyutina_ds/task01/main.py
> +    for i in range(1, len(maze_map)):
Хотя вроде как основная обработка находится в этом месте кода, тогда что делает предыдущий цикл?

2021-03-20 18:20 UTC, Dsin72 commented on sinyutina_ds/task01/main.py
> +    vertex_map = [['' for i in range(len(row))] for row in maze_map]
Показалось наиболее логичным решением на тот момент. В новой версии переделала.

2021-03-20 18:22 UTC, Dsin72 commented on sinyutina_ds/task01/main.py
> +    for i in range(len(maze_map[0])):
Решила разделить обработку первой строки и всех последующих, тк при обработки первой строки не имеет смысла просмотр соседнего элемента из предыдущей строки.

2021-03-20 18:33 UTC, Dsin72 commented on sinyutina_ds/task01/main.py
> +        path = input()
Исправила в новом коммите

2021-03-20 18:34 UTC, Dsin72 commented on sinyutina_ds/task01/main.py
> +
Исправила в новом коммите

2021-03-20 18:34 UTC, Dsin72 commented on sinyutina_ds/task01/main.py
> +    for i in range(1, len(maze_map)):
Исправила в новом коммите

2021-04-04 06:20 UTC, merged