Сдаю первый кусок дз
xthebat/iu4-2k21-mlni pull request #9
Opened 2021-03-14 20:08 UTC by ZloiZebroo

Сделал генерацию оптимизированного графа по тхт файлу и сохранение его в json

2021-03-17 05:50 UTC, xthebat requested changes
"+" Кода написан в соответствии с PEP8, нет ни одной ругани от PC
"+" Структура функций неплохая
"+" Нейминг в целом норм

"-" Дизайн классов - жесть
"-" Дизайн возвращаемых аргументов - жесть

"-" Не работает на лабиринте:
```
11
11
```
"-" Не правильно работает на лабиринте - должно быть 9 узлов, в результате 5 узлов
```
111
111
111
```

Итого:
Необходима правильна работа на приведенных лабиринтах и юнит-тесты. Рефакторинг по желанию и после исправления не правильной работы.

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +        file = open(txt_path, "rt")
Файлы (ресурсы) лучше использовать с with - это гарантирует, что они будут закрыты

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +    def to_json(self):
Немного забавно, что при чтении лабиринты вы передаете имя входного файла, а при записи - нет. Даже в "костыльном коде" методы и функции лучше оформлять так, чтобы передавать в них аргументы, а не использовать хардкоженные переменные

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +class Maze:
Лучше (не знаю почему, но мне кажется PyCharm так говорит) явно наследоваться от object

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +    # Читаем лабиринт из тхт файла
Такие комментарии никогда не пишите, это прекрасно видно уже из вашего кода, naming достаточно хороший. Комментарии такого рода только усложняют чтение кода. Он имел бы смысл только в том случае, если у вас вдруг в `load_from_txt` оказалось бы что-то еще (но естественно так лучше не делать :))

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +        self.adj = None
Кстати, вопрос к нейменгу и комментариям, вот тут они были бы полезны. В чем отличие `self.adj` от `self.adj_matrix`?

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +    maze = Maze()
Касательно класса Maze - его архитектурная надобность здесь стремится к нулю. Единственное, что он агрегирует для совместной обработки - это self.nodes и self.adj
В то время когда вы строите матрицу связанности поля класса никак не использованы, все равно просто передается в отдельную функцию. Если уже делать классы - я бы в первую очередь озаботился бы именно классом для матрицы связанности, так как это наиболее нагруженная сущность во всем коде.

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +import json
Структура директорий неправильна - первое ДЗ должно быть в папке task01

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +    maze.load_from_txt(maze_2)
Действительно в методе оказалась не только загрузка, но и парсинг лабиринта. В целом наверное стоило бы разделить эти методы. Вынести все, что относится к чтению файла во вне. Кроме этого в данном случае лучше бы как раз подошли classmethod или staticmethod (фабричный метод). То есть, метод который создает объект из какой-то заданной сущности.

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +    print(f'Последний индекс по Х: {last_x}')
У вас логирование где-то на русском, где-то на английском (и комментарии тоже). Лучше уже придерживаться одного языка во всей программе. Общепринятым конечно является английский

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +    for y in range(len(data)):
#itertools
Я бы заюзал здесь rangend, который писал на семинарах

#Нейминг
Когда работает с матрицами очень не советую именовать индексы x, y. Потому что, как вы могли заметить они идут в другом порядка по отношению к обычной геометрии. Кроме этого ось Y еще и вниз направлена. Поэтому лучше использовать всегда терминологию row и col (r, c).

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +def find_possible_ways(data, point):
Вот здесь начинает прослеживаться "ошибка" дизайна классов. У вас в нескольких функция появляется одна и та же операция, получить last_x, last_y. Если уж погнали делать классы - обернули data - в класс Matrix, у которого уже сделали бы метода (или так как матрица не меняется) предвычислили бы кол-во ROW и COL.

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +    last_y = len(data) - 1
Здесь и выше и ниже: не очень хорошо использовать last.... в контексте матриц. Обычно используется размер или количество row, col. А когда нужен ласт, то делают  - 1

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +    x, y = point
Для чего вы передаете в функцию tuple? По факту только нагрузили ваш код лишними действиями и тут даже вопрос не столько к скорости сколько к readability. Зачем-то собираете xy в tuple, чтобы следующей операцией его разделить.

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +# Возможные пути по которым можно пойти от точки
Вопрос к неймингу: конечно это навязывание, но я бы назвал это соседями, так как один шаг - сложно назвать путем. Либо связями. Пути - очень запутывают.

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +            nodes, ways, is_node, point = get_node(x, y, data, nodes)
#Дизайн_классов
Вы сделали класс точки Point, но используете его очень ограниченно и получается, что из функции возвращаете кучу переменных через тупл. Одна из которых - это bool (это вообще ужасно). Почему не назвать класс Point, классом Node и не запихать туда все эти переменные?
Ну is_node поменять на is_simple например? А ways я бы заменил на links - это же связи с соседями.

#Неправильно_использован_tuple
Возвращать из функцию кучу переменных через тупл - это прям кричащее место, где нужен просто правильный дизайн классов. Это вносит жуткую путаницу в код и скорее всего через пару недель вы сами забудете, что эта функция возвращала. Обращайте на такие места и постарайтесь больше так не делать в коде (особенно когда, что-то будет писать в прод). Более двух переменных не возвращайте через тупл.

#Возврат_входного_аргумента
Для чего в данном случае вы возвращаете nodes? Он является аргументом функции и изменяется в ней. Вы нигде не используете эту функцию как было у меня в примере, чтобы не инициализировать результат работы. На мой взгляд это просто не нужно действие

PS: я видел, что конкретно эта функция find_nodes не юзается - это кстати тоже плохо, когда отдаете код в прод, такие вещи нужно убирать, мертвый код усложняет читаемость.

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +
nodes я бы объявил прямо здесь и уже везде передавал как словарик со нодами графа

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +    wte = WaysToExplore(ways, previous_point)
Вот здесь вы как раз оборачиваете точку еще в один класс у которого прописаны соседи. Почему это все:
1. Не упихать в саму точку?
2. Сразу не вернуть из get_node?

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +    if len(dc.next_explore) > 0 and dc.point.id < 10:
#Комментарии
Что за сравнение с 10? Почему нету комментария по этому поводу

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +def adjacency_matrix(nodes, adj):
Если я все правильно понял, то здесь эффектиность - отрицательная :)

```python
def adjacency_matrix(nodes, adj):
    size = len(adj)
    matrix = [[None] * size for _ in range(size)]
    for node, links in adj.items():
        row = int(node)
        for other, length in links.items():
            col = int(other)
            matrix[row][col] = length
    return matrix
```
разве так не проще?

И зачем вообще словарь nodes? Не очень понял

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +            except KeyError:
Если есть возможность передавать полезную информация не через исключения - лучше тогда их не использовать. Исключения всегда медленнее обычных сравнений. То есть в данном случае лучше использовать get()

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +class DataCase:
Что касается этого класса.... на мой взгляд - он все очень усложняет. Проблема в том, что когда начинаешь разбираться с функцией `recursive_explorer` возникает оооочень большая связанность. Так как получается так, что эти данные все фактически передаются как изменяемые. Ну то есть условно вы "передали по указателю". Получается в каждый из них может в любой момент измениться и что сейчас с ними происходит ... сложно понять.

Первое чтобы я переделал при рефакторинге - это отказался бы от этого класса и переделал бы на просто переменные в функции recursive_explorer. Дальше уже по взаимосвязям смотрел, что объединить в классы и как

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +                # Если больше нет путей потыкаться, ливаем с катки
Смотри так и бан пропишут на 30 минут

2021-03-17 05:50 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +                point_id = list(nodes.values()).index([x, y])
Вот тут бы пригодился инвертированный словарь. Это кстати в сторону того, что не очень хорошо задизайнен nodes во время преобразования.

Он отображает номер узла в индексы клетки. Мне кажется, что нужно как раз наоборот, так операция получить номер клетки по имени узла - судя по коду вообще очень редкая. 

А пара индексов - это уникальное значение. Кроме того, когда дампишь в json все равно численные ключи преобразовал в str

2021-03-17 07:09 UTC, ZloiZebroo commented
Что такое дизайн классов?

2021-03-17 07:18 UTC, xthebat commented
Это то как вы спроектировали вашу структуру/архитектуру классов. Какой класс с кем связан, для чего он и какие методы у него и как они должны быть использованы.

2021-03-17 07:18 UTC, xthebat commented
И да насчет лабиринта 3х3, я видимо ошибся, всё правильно - должно быть 6 узлов

2021-03-17 13:53 UTC, ZloiZebroo commented on ZloiZebroo/Dz01/maze.py
> +        self.adj = None
`self.adj` - связи между графами
`self.adj_matrix` - матрица смежности

2021-03-17 14:06 UTC, ZloiZebroo commented on ZloiZebroo/Dz01/maze.py
> +    maze.load_from_txt(maze_2)
Я посчитал, что целевой сущностью в данном случае является сам граф. Методы `load_from_txt`  и `load_from_json` дают на выходе один и тот же целевой граф, который мы хотели получить, а парсинг тхт файла - побочный эффект при чтении данных в таком формате.

2021-03-20 09:20 UTC, ZloiZebroo commented on ZloiZebroo/Dz01/maze.py
> +                point_id = list(nodes.values()).index([x, y])
Да, с инвертированным словарём было бы удобнее, но зачем таскать с собой инвертированную копию словаря, если нужную инфу можно вытащить из уже имеющегося. Если текущий словарь заменить на инвертированный, то будет не такой красивый выходной json. Там координаты узлов и пути связанны как раз по номеру узла.

Численные ключи преобразовываются в строки из-за особенности работы `json.dumps() `.  Жертвуя численными ключами, получаем красивый отсортированный json файл с отступами.

2021-03-20 09:26 UTC, ZloiZebroo commented on ZloiZebroo/Dz01/maze.py
> +    if len(dc.next_explore) > 0 and dc.point.id < 10:
Осталось от дебага, уже поправил. Чтобы функция не улетала в бесконечный цикл, стоит ограничение на 10 id узлов.

2021-03-20 09:37 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +                point_id = list(nodes.values()).index([x, y])
Выгрузка в файл операция достаточно редкая, а вот поиск элементов у вас выполняется почти каждую рекурсию, если не чаще. Поиск по значениям в словаре это крайне не эффективно по сравнению поиска по ключам. Поэтому лучше использовать в алгоритме инвертированный словарь, а при выгрузке только для сохранения инвертировать его временно в памяти.

2021-03-20 10:35 UTC, ZloiZebroo commented on ZloiZebroo/Dz01/maze.py
> +                point_id = list(nodes.values()).index([x, y])
TypeError: unhashable type: 'list'

2021-03-20 10:45 UTC, ZloiZebroo commented on ZloiZebroo/Dz01/maze.py
> +                point_id = list(nodes.values()).index([x, y])
решаемо

2021-03-20 11:08 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +                point_id = list(nodes.values()).index([x, y])
Используйте tuple - он не изменяем и хешируем

TLTR: Правильно, потому что в python list - нехешируемый (я об это говорил). То есть от объектов типа list посчитать хешь нельзя. А этот самый хеш нужен, чтобы объект был ключом словаря (или мог быть добавлен в множество). Хеш позволяет значительно сократить время поиска объекта в коллекции. У словаря нету хеша - так как словарь изменяемый тип. Представьте, что если бы список был хешируем, то вы могли бы добавить в словарь список, а потом по ссылке его изменить, так чтобы он стал равен другому объекту. У вас в итоге получиться словарь с двумя одинаковыми ключами - это порушит все.

2021-03-20 11:10 UTC, ZloiZebroo commented on ZloiZebroo/Dz01/maze.py
> +                point_id = list(nodes.values()).index([x, y])
я уже list просто перевёл в string и всё завелось)

2021-03-20 11:29 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +                point_id = list(nodes.values()).index([x, y])
Ох, я понимаю, что это учебная задача :) и особо прироста в скорости не будет. Но вы когда лист к строке приводите, чтобы как ключ использовать - это прям жуткий костыль и опять трата процессора. Почему сразу туплы не делать? Это как раз идеальный случай где они нужны. У вас координаты и никогда не меняются

2021-03-20 11:33 UTC, ZloiZebroo commented on ZloiZebroo/Dz01/maze.py
> +                point_id = list(nodes.values()).index([x, y])
Вы говорили, что туплы плохо сочетаются с json. Их всё равно потом придётся в список перегонять.

2021-03-20 11:39 UTC, ZloiZebroo commented on ZloiZebroo/Dz01/maze.py
> +                point_id = list(nodes.values()).index([x, y])
Перевёл вектор координаты в туплы и сделал в конце конвертацию в массив

2021-03-20 11:43 UTC, xthebat commented on ZloiZebroo/Dz01/maze.py
> +                point_id = list(nodes.values()).index([x, y])
Да, плохо сочетаются с json - но перегнать в файл - это не очень часто (и текущей задаче и в целом, когда сохраняем что-то в файл, скорости ждать не приходится). А вот обращение в памяти к координатам во время рекурсии постоянно, поэтому тут стоит экономить процессор. А перед сохранением уже конвернтуть во что удобнее будет сохрнять

2021-03-21 18:11 UTC, ZloiZebroo commented
Поправил предыдущие замечания и сделал доработки:

- Добавил юнит тесты
- Добавил поиск кратчайшего пути Дийкстрой
- Использовал Rengend
- Удалил класс Maze
- Теперь работает на лабиринте 2х2 и 3х3
- Добавил поиск кратчайшего пути с удалением стенки
- Наследовался от object в классах
- Новый дизайн классов
- Новый преобразователь в матрицу смежности
- Убрал не используемую функцию Find_nodes
- Переименовал пути в соседей
- Логирование на английском
- Передача пути сохранения файла через аргумент
- Поправил структуру папок
- С файлами использовал with

2021-03-22 15:42 UTC, xthebat reviewed
Тесты я посмотрел, попробую позадавать разные лабиринты, если на них пройдет, то тогда принято. Но с классами тяжеловато :) 
Вот тут основные принципы расписаны, без примеров, к сожалению:
https://tproger.ru/translations/oop-principles-cheatsheet/

Ну наверное вот тут неплохо про классы (ООП) с примерами, но многобукв
https://realpython.com/inheritance-composition-python/

2021-03-22 15:42 UTC, xthebat commented on ZloiZebroo/task01/maze.py
>  # получить узел, если это узел
В прошлый раз не обратил внимание: документация в питоне пишется внутри функции в тройных ковычках, например:

```python
def say_meow(arg):
    """this function just say meow"""
    print("meow")
```

2021-03-22 15:42 UTC, xthebat commented on ZloiZebroo/task01/maze.py
> +def get_node(point, matrix, nodes):
С этой функцией очень страшно - она называется get_node (получить узел), но внутри меняет список узлов. Это не очень хорошо. То есть нужно стараться писать код так, чтобы не перегружать различной функциональностью одну функцию. Кроме этого - эта функция зовется в find_start_node и тоже начинает модифицировать список узлов. Я хотел распутать этот узел - но после модификации узлов стало совсем страшно, частично можно посмотреть здесь:
https://github.com/xthebat/iu4-2k21-mlni/commit/7abd374f6f6c645afb42de5d952e41bae880340c

2021-03-22 15:42 UTC, xthebat commented on ZloiZebroo/task01/maze.py
> +    for r in range(len(matrix.data)):
У вас же есть columns, rows

2021-03-22 15:42 UTC, xthebat commented on ZloiZebroo/task01/maze.py
> +                # x = wte.ways_to_explore[0][0]
мертвый код нужно удалять, возможно смотрю не последний коммит)

2021-03-22 15:42 UTC, xthebat commented on ZloiZebroo/task01/maze.py
>          self.matrix = None
Во тут я потерялся, последний коммит в main в вашем репозитории другой код по сравнению с этим коммитом. Причем если этот коммит не последний, то в нем Graph реализован лучше. 

То что я увидел в последнем коммите, вы создаете просто Graph, а потом ему накидываете на поля уже значения, которые получены в какой-то другой сторонней функции. Это фактически рушит принцип ООП. Смысл же в том, что у нас есть данные методы их обработки и это в одном месте. 

То есть, если у вас ситуация, что для создания объекта нужны какие-то данные, то эти данные должны идти в конструктор, а не присваиваться где-то потом. Если для вычисления чего-либо нужные какие-то данные, то скорее всего эти функции это методы класса в котором данные содержаться. К какому классу отнести методы, если вроде как нужно для обоих классов - смотрим по связанности с какими данными методы связаны больше к тем классам и относим

2021-03-22 15:49 UTC, ZloiZebroo commented on ZloiZebroo/task01/maze.py
>          self.matrix = None
Вот тут актуальная версия. Вроде бы в этом реквесте она же должна быть, потому что он подтягивает её из main

https://github.com/ZloiZebroo/iu4-2k21-mlni/commit/033089f8e60c4d51c1e7ec97eb8878103e11e5db

2021-03-22 16:00 UTC, ZloiZebroo commented on ZloiZebroo/task01/maze.py
> +def get_node(point, matrix, nodes):
`get_node` автоматом добавляет узел в список узлов, чтобы потом не надо было это делать вручную. Сразу его и находит и кладёт в "корзинку", а остальным функциям остаётся только её пинать в нужный момент.  

`find_start_node` находит первый попавшийся узел, чтобы начать с него обход лабиринта.

2021-03-26 07:19 UTC, xthebat commented on ZloiZebroo/task01/maze.py
>          self.matrix = None
Входной файл:
```
11110111
00000001
11110111
11110111
```

код теста:
```python
    def test_maze_08(self):
        data = graph.load_from_txt('../maze_08.txt')
        ans1, ans2 = graph.find_start_node(dict(), data.matrix)
        print(data)
        print(ans1)
        print(ans2)
        print("meow")
```

Смотрю в дебаге:
![image](https://user-images.githubusercontent.com/2856140/112596244-9b42b200-8e1c-11eb-92ce-3caf0e38e299.png)

Вопросы и комментарии:
- Ноды до поломки - ок
- Матрицы до поломки - ок
- Стенки для поломки - судя по всем все возможные, можно ломать только одну.
- Я так понимаю алгоритм пока не строит пути? Если строит, то как их получить?

2021-03-26 07:22 UTC, ZloiZebroo commented on ZloiZebroo/task01/maze.py
>          self.matrix = None
Путь печатается в консоль

2021-03-26 07:42 UTC, ZloiZebroo commented on ZloiZebroo/task01/maze.py
>          self.matrix = None
Я так понял, в этом лабиринте проверяется случай, когда без поломки стенки невозможно добраться до выхода. Я такой вариант исключил из алгоритма и предполагал, что поломка стенки будет позволять сокращать уже имеющийся путь. Как раз мёртвая функция  `find_nodes` из предыдущих комитов несла в себе идею просветки всего лабиринта насквозь и составления карты узлов заранее, но я посчитал, что такого случая не будет, потому что кому надо стучаться в изолированные узлы, если в них всё равно не попасть (без поломки стенки).

2021-03-26 09:11 UTC, xthebat commented on ZloiZebroo/task01/maze.py
>          self.matrix = None
Тогда не нашел, где есть тест на сам путь. То есть печатается - окей, но нужно бы тест. В этом тесте тогда сразу можно поиграться.
В итоге:
- поиску пути как я понял есть? Если так, то нужно вынести в тест
- насколько помню говорил, что в исходном лабиринте пути может не быть :) Ну окей, если забыл, будем считать, что путь должен быть и в исходном лабиринте. 
- Если поиск пути с поломкой стенки есть, вынеси пожалуйста это в отдельный тест, где проверяется найденный путь.

2021-03-26 19:26 UTC, ZloiZebroo commented
Как этим пользоваться:

`load_from_txt` загружает оптимизированный граф 
`shortest_way` позволяет найти кратчайший путь между двумя узлами этого графа

`shortest_way(0, 3, graph, brake_wall=True)`
`0` - id начального узла
`3` - id конечного узда
`graph` - загруженный с помощью `load_from_txt` граф
` brake_wall=True` - параметр, позволяющий выбрать режим поиска кратчайшего пути. В положении True, будет производится поиск с возможностью удаления одной стенки. При этом, очерёдность id узлов не поменяется, а новообразовавшиеся узлы добавятся в конец словаря `nodes`.

2021-03-26 20:39 UTC, ZloiZebroo commented
Что нового:

- Работает на графе, в котором изначально невозможно добраться до выхода без пробития стенки
- Появились тесты для поиска пути
- Работает на пустом графе
- В комментарии выше инструкция как с этим играться 
- Кратчайший путь и его длинна теперь хранятся в объекте `Graph`, а не только в консоли

2021-04-04 06:12 UTC, merged